#include <stdio.h>
int main(){
 int a,b;
 printf("hello world without semi colomn;\n with two method\n 1) while loop : enter 1 for this\n 2) if statement: press 2 for this ");
 scanf("%d",&a);
 if (a==2){
     if(printf("hello world")){}
 }
 else{
    while(!printf("hello wolrd")){}             

 }
 printf("A broken heart is all that's left\nI'm still fixing all the cracks\n Lost a couple of pieces when\nI carried it, carried it, carried it home\n… I'm afraid of all I am\nMy mind feels like a foreign land\nSilence ringing inside my head\nPlease carry me, carry me, carry me home\n… I've spent all of the love I saved\nWe were always a losing game\nSmall town boy in a big arcade\nI got addicted to a losing game\n\n… Oh\n\nOh\n\nAll I know, all I know\n\nLoving you is a losing game\n\n… Do you love me, love me not?\n\nGiving pieces from my heart\n\nTomorrow's coming and has gone\n\nStill I carried, I carried, I carried on\n\n… Oh\n\nOh\n\nAll I know, all I know\n\nLoving you is a losing game\n\n… Oh\n\nOh\n\nAll I know, all I know\n\nLoving you is a losing game\n\n… I don't need your games, game over\n\n… Get me off this rollercoaster\n\n… Oh\n\nOh\n\nAll I know, all I know\n\nLoving you is a losing game\n\n… Oh\n\nOh\n\nAll I know, all I know\n\nLoving you is a losing game")
 scanf("%d",&b);
 return 0;
}